### ISSUE TITLE
Program using your imgwarp.cpp

### ISSUE THREAD

**Issue by zappybiby** [bethesirius/ChosunTruck#3]
When running the release x64 exe, I ran into this error: 

OpenCV Error: Assertion failed (ssize.area() > 0) in cv::remapBilinear, file C:\Users\bishnois.VITECNET\Downloads\opencv-master\modules\imgproc\src\imgwarp.cpp, line 3832

So I removed line 3832 (because it will run without it) in my imgwarp.cpp, however the error still appears. I don't know where it's referencing your imgwarp and I don't know how to change it so that it uses my imgwarp.cpp instead of yours.

**Comment by zappybiby** [comment]
may have fixed it with #https://github.com/ajchili/ChosunTruck/commit/9c42c4e20904be6cc3608b9ab81b4dd5804e57cc

Getting a new error: 
 ``OpenCV Error: The function/feature is not implemented
(You should explicitly call download method for cuda::GpuMat object) in
cv::_InputArray::getMat_, file
C:\Users\bishnois.VITECNET\Downloads\opencv-master\modules\core\src\matrix.cpp,
line 1232``

**Comment by chi3236** [comment]
Did you run ETS2 with window mode? I think that error might be occured because you execute the ETS2 with full screen. Please try it with window mode (recommended resolution is 1024*768)

Thank you for your interest on our project, but unfortunately our program does not work appropiate on Windows. We tried to control the truck with WM_KEYDOWN function, but we could not handle the truck with virtual key input.

Please run our program in Ubuntu, and it will work properly with 1920 * 1080 screen resolution and 1024 * 768 window mode ETS2.

**Comment by zappybiby** [comment]
Thanks! I will switch to Ubuntu
