### ISSUE TITLE
Windows-based ChosunTruck Steering Problem

### ISSUE THREAD

**Issue by mrasyidaqmar** [bethesirius/ChosunTruck#33]
Hi, thank you for the amazing work! 

I have compiled and run the program in Windows, and it can show the output result on the terminal window, Road image output and Lines image output, as you can see on the image I show below:
![chosuntruck-snapshot](https://cloud.githubusercontent.com/assets/1209717/23738732/1450a390-04de-11e7-8291-42cd3a1e5eb9.png)

I think it can produce the output of the steering value (+/- pixel's unit), but it seems the steering output does not control the truck's steer, I stil have use my mouse to control the truck.

I have altered the "control.ssi" file, resized the window size, and set the control setting into keyboard+mouse. 
If you know what else do I miss, I will be very happy to hear it.

Thanks!

**Comment by mrasyidaqmar** [comment]
In the main.cpp file, I have a doubt which part of the code actually control the steer.
is it this one? 
"SetCursorPos(moveMouse, height / 2);"

**Comment by mrasyidaqmar** [comment]
This is my control.sii file looks like:
![controlsii](https://cloud.githubusercontent.com/assets/1209717/23739373/b92a57be-04e1-11e7-9737-9e8b01418a85.png)

**Comment by mrasyidaqmar** [comment]
This is my controller setting:
![controller-setting](https://cloud.githubusercontent.com/assets/1209717/23739428/14fa5e5e-04e2-11e7-910e-d77d33c30c25.png)

**Comment by mrasyidaqmar** [comment]
I just realized something. When the mouse cursor is outside the ETS2 window, the cursor is actually moving!
However, when I put the ETS2 window as the main window, the cursor does not seem to move.
I am not sure yet how to solve this, but if anyone knows the solution, please let me know. I will also report the solution if I found it.

**Comment by zappybiby** [comment]
The problem is that controls.sii is not set to read-only, and is being overwritten every time you start the game. 

The reason the program works outside of the program is because it uses the Win32 API to control the mouse. However, DirectInput caused issues with the movement of the mouse and I was unable to resolve the issue. Instead, I am editing the controls.sii to allow the program to accept mouse movement mediated by WIN32 calls. 

So, to fix your problem, make sure your file is not in read-only, then make the necessary edits, then save and make the file read-only. You might also have to save your file in-game or something like that.

**Comment by mrasyidaqmar** [comment]
Wow, great! thanks a lot! I will try this solution and update the result!

**Comment by simjaecheol** [comment]
Closed issue :)

**Comment by mrasyidaqmar** [comment]
Yes, the solution works. Nice :). In addition, I may have to add a minor detail: Open the game, find the newly created/updated "config.ssi" file (note that the file can be more than one saved in a different directories depend on your saved game, select the proper one) based on your corresponding saved/ongoing game, edit it based on the tutorial. Close the game, and open/start the game once more. That's it :).
